apiVersion: v1
kind: Secret
metadata:
  name: openeyes-passwords
type: Opaque
stringData:
  mysql-root: example
  mysql-pass: openeyes
---
apiVersion: v1
kind: Secret
metadata:
  name: openeyes-ssh-key
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: |
    -----BEGIN RSA PRIVATE KEY-----
    EXAMPLE
    -----END RSA PRIVATE KEY-----
